# Generated by Django 2.2 on 2022-04-07 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTCData',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, help_text='common primary key for all the tables', primary_key=True, serialize=False)),
                ('mpan', models.BigIntegerField()),
                ('meter_serial_number', models.CharField(max_length=16)),
                ('meter_reading', models.CharField(max_length=16)),
                ('imported_file_name', models.CharField(max_length=128)),
                ('file_imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dtc_data',
            },
        ),
    ]
